# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7fc93be55cb82b34802ea255a13a4716e36ed15a34bdc511d5f4141d61b31c11dac401a9d820cf5c77b4f024ac1a031f6e8f4123359546199e5144f466fdc874

test:
  secret_key_base: 43ff0e4c9e776fc4a4ba21059155dea4eb8a0897475e55305cfcbc35478932c7931c341932a6671c3db523fabbd3e93c2881459e0ec345f030b67c2e7c33a4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
